config/routes.rb
Rails.application.routes.draw do

  resources :connect 
  resources :listings do
    resources :devices
    resources :reservations
    member do
      put "automation"
    end
  end
  
  root "connect#index"
  get "/oauth/callback", to: "connect#authorize"
  
end

app/models/listing.rb
class Listing < ActiveRecord::Base
    has_many :devices
    has_many :reservations
    validates_presence_of :name
    after_initialize :init
    
    def init
        self.time_created ||= Time.zone.now
        self.automation ||= 0
    end
end

app/controllers/listings_controller.rb
require 'json'
class ListingsController < ApplicationController

    def authenticated?
        session[:access_token]
    end
    
    def listing_params
        params.require(:listing).permit(:name, :time_created)
    end
    
    def show
        if !authenticated?
          redirect '/'
          return
        end
        @listing = Listing.find(params[:id])
        @devices = @listing.devices
        @reservations = @listing.reservations
    end
    
    def index
        @listings = Listing.all
    end
    
    def new

    end
    
    def edit
        @listing = Listing.find(params[:id])
    end
    
    def create
        begin
            @listing = Listing.create!(listing_params)
        rescue ActiveRecord::RecordInvalid
            flash[:deny] = "Name is required for new listing."
            redirect_to listings_path
            return
        end
        
        flash[:success] = "Listing #{@listing.name} was created successfully!"
        redirect_to listings_path
    end
    
    def destroy
        @listing = Listing.find(params[:id])
        @devices = Device.where(listing_id: @listing.id)
        @reservations = Reservation.where(listing_id: @listing.id)
        
        listToSend = {}
        
        @devices.each_with_index do |device, i|
            temp = "#{device.device_type}.#{device.id}"
            listToSend[i] = temp
        end
        @reservations.each do |res|
            res.destroy
        end
        puts listToSend.to_json
        endpoints_uri = 'https://graph.api.smartthings.com/api/smartapps/endpoints'
        token = session[:access_token]
    
        url = URI.parse(endpoints_uri)
        req = Net::HTTP::Get.new(url.request_uri)

        # we set a HTTP header of "Authorization: Bearer <API Token>"
        req['Authorization'] = 'Bearer ' + token
    
        http = Net::HTTP.new(url.host, url.port)
        http.use_ssl = (url.scheme == "https")

        response = http.request(req)
        json = JSON.parse(response.body)
        uri = json[0]['uri']
        
        newUrl = uri + "/deleteDevices"
       
        deleteUrl = URI.parse(newUrl)
        
        deleteHttp = Net::HTTP.new(deleteUrl.host, deleteUrl.port)
        deleteHttp.use_ssl = true
       
        
        deleteReq = Net::HTTP::Post.new(deleteUrl.request_uri, 'Content-Type' => 'application/json')
        deleteReq['Authorization'] = 'Bearer ' + token
        deleteReq.body = listToSend.to_json
        #deleteReq.set_form_data('id' => @device.id, 'type' => @device.device_type)
        #we set a HTTP header of "Authorization: Bearer <API Token>
        
        response = deleteHttp.request(deleteReq)
        case response.body
        when "Devices Deleted"
            @devices.each do |device|
                device.destroy
            end
            @listing.destroy
            flash[:success] = "Listing '#{@listing.name}' deleted"
        else
            flash[:deny] = "Error deleting devices in Listing #{@listing}"
        end
        redirect_to listings_path
    end
    
    def automation
        @listing = Listing.find(params[:id])
        @reservations = @listing.reservations
        @devices = @listing.devices
        currentTime = Time.zone.now
        if (@listing.automation == 1)
            @listing.automation = 0
            @listing.save
            
        else
            @listing.automation = 1
            @listing.save
            
            lightsOff = true
            @reservations.each do |res|
                if (currentTime.between?(res.start_date, res.end_date))
                    lightsOff = false
                end
            end
            if (lightsOff)
                listToSend= {}
                @devices.each_with_index do |dev, i|
                    if(dev.device_type == "Light")
                        listToSend[i] = "#{dev.id}"
                    end
                end
                unless (listToSend.length == 0)
                    endpoints_uri = 'https://graph.api.smartthings.com/api/smartapps/endpoints'
                    token = session[:access_token]
                
                    url = URI.parse(endpoints_uri)
                    req = Net::HTTP::Get.new(url.request_uri)
                    
                    # we set a HTTP header of "Authorization: Bearer <API Token>"
                    req['Authorization'] = 'Bearer ' + token
                
                    http = Net::HTTP.new(url.host, url.port)
                    http.use_ssl = (url.scheme == "https")
                
                    response = http.request(req)
                    json = JSON.parse(response.body)
                    uri = json[0]['uri']
                        
                    newUrl = uri + "/turnOffLights"
                       
                    lightUrl = URI.parse(newUrl)
                        
                    lightHttp = Net::HTTP.new(lightUrl.host, lightUrl.port)
                    lightHttp.use_ssl = true
                       
                        
                    lightReq = Net::HTTP::Post.new(lightUrl.request_uri, 'Content-Type' => 'application/json')
                    lightReq['Authorization'] = 'Bearer ' + token
                    lightReq.body = listToSend.to_json
        
                    response = lightHttp.request(lightReq)
                    puts response.body
                    case response.body
                    when "Lights Off"
                        flash[:success] = "Lights turned off!"
                    else
                        flash[:deny] = response.body
                    end
                end
            end
        end
        redirect_to listing_path(@listing)
    end
end

app/views/listings/index.html.erb
<!DOCTYPE html>
<html>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <body>
    <div class="container" style = "height: 800px">
      <div>
       <h1>Listings</h1>
        <table id="listings">
         <% if flash[:success] %>
        <div id="success">
          <%= flash[:success] %>
        </div>
         <% elsif flash[:deny] %>
        <div id="deny">
          <%= flash[:deny] %>
        </div>
        <% end %>
          <thead>
            <tr>
              <th>ID</th> 
              <th>Name</th>
              <th>Devices</th>
              <th>Reservations</th>
              <th>Date Created</th>
              <th>Automation</th>
              <% if not @listings.all.size == 0 %>
                <th>More Info</th>
              <%end%>
            </tr>
          </thead>
          <tbody>
            <% @listings.each do |listing| %>
            <% if listing.id % 2 == 0%>
              <tr bgcolor = '#E7D9C3'>
            <% else %>
              <tr>
            <% end %>
                <td>
                  <%= listing.id %>
                </td>
                <td>
                  <%= listing.name %>
                </td>
                <td>
                  <%= listing.devices.size %>
                </td>
                <td>
                  <%= listing.reservations.size %>
                </td>
                <td>
                  <%= listing.time_created.strftime("%B %d, %Y ") + listing.time_created.strftime("%H:%M") %>
                </td>
                <td>
                  <% if (listing.automation == 1) %>
                  On
                  <% else %>
                  Off
                  <% end %>
                </td>
                <td id="detail">
                  <%= link_to "Reservations and Devices", listing_path(listing) %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
       
      </div>
     
    </div>
     <div id="footer">
        <%= button_to 'Add New Listing', new_listing_path, :method => :get %>
        <p style="bottom: 0px; float: right; font-size: 90%;">Created by Grant Hoffmann</p>
    </div>
  </body>
</html>

app/views/listings/new.html.erb
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
<h2>Create New Listing</h2>

<%= form_tag listings_path, :method => :post do %>
  <%= label :listing, :name, 'Listing Name' %>
  <%= text_field :listing, :name %>
<div id = "footer">
<table>
  
<% end %>

<td><%= button_to 'Go Back', listings_path, :method => :get %></td>
<td><%= submit_tag 'Create Listing' %></td>
</table>
</div>

app/views/listings/show.html.erb
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
<html>
<head>
<h1>Details about <%= @listing.name %> </h1>
 
 <div style="display: in-line">
  <table>
  <th><%= button_to 'Add New Reservation',  new_listing_reservation_path(:listing_id => @listing.id), :method => :get %></th>
  <th><%= button_to 'Add New Device', new_listing_device_path(:listing_id => @listing.id), :method => :get %></th> 
  <th>
    <%if (@listing.automation == 1)%>
        <%= button_to 'Turn Automation OFF', automation_listing_path, :method => :put%>
      <% else %>
        <%= button_to 'Turn Automation ON', automation_listing_path, :method => :put%>
    <% end %>
  </th>
  </table>
</div>
<div style ="display: block; height: 100px">
  <h2 style = "float: left; margin: 20px"> Reservations</h2>
  <h2 style = "float: right; margin: 20px"> Devices</h2>
 </div>
 </head>
<body>
  <% if flash[:success] %>
        <div id="success">
          <%= flash[:success] %>
        </div>
         <% elsif flash[:deny] %>
        <div id="deny">
          <%= flash[:deny] %>
        </div>
  <% end %>
<div style = "display: block;">
<table id="reservations" style = "float: left; display: table">
  <thead>
    <th>
      Reservation Name
    </th>
    <th>
      Start Date
    </th>
    <th>
      End Date
    </th>
  </thead>
  <tbody>
        <% @reservations.each do |res| %>
          <tr>
            <td>
              <%= link_to res.name, listing_reservation_path(res, :listing_id => res.listing_id) %>
            </td>
            <td>
              <%= res.start_date.strftime("%B %d, %Y")%>
            </td>
             <td>
              <%= res.end_date.strftime("%B %d, %Y") %>
            </td>
          </tr>
        <% end %>
  </tbody>
</table>


<table id="devices" style = "float: right; display: table">
  <thead>
    <th>
      Device Name
    </th>
    <th>
      ID
    </th>
  </thead>
  <tbody>
        <% @devices.each do |device| %>
          <tr>
            <td>
              <%= link_to device.name, listing_device_path(device, :listing_id => device.listing_id) %>
            </td>
            <td>
              <%= device.id %>
            </td>
          </tr>
        <% end %>
  </tbody>
</table>
</div>


</body>



<div id ="footer">
<table id = "buttons_table" >
  <th><%= button_to 'Back to Listings', listings_path, :method => :get %></th>    
  <th><%= button_to 'Delete Listing', listing_path(@listing), :method => :delete %></th>
  
</table>
</div>
</html>