config/routes.rb
Rails.application.routes.draw do

  resources :connect 
  resources :listings do
    resources :devices
    resources :reservations
    member do
      put "automation"
    end
  end
  
  root "connect#index"
  get "/oauth/callback", to: "connect#authorize"
  
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
    belongs_to :listing
    validates_presence_of :name
    validates_presence_of :start_date
    validates_presence_of :end_date
    after_initialize :init
    
    def init
        self.time_created ||= Time.zone.now
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
    
    def reservation_params
        params.require(:reservation).permit(:name, :start_date, :end_date)
    end
     
    def new
        @listing = Listing.find(params[:listing_id])
    end

    def create
        @timeCreated = Time.zone.now
        @listing = Listing.find(params[:listing_id])
        localParams = reservation_params
        begin
            if (@timeCreated.between?(localParams[:start_date], localParams[:end_date]) or (localParams[:start_date] > localParams[:end_date]))
                flash[:deny] = "Invalid reservation date ranges"
            else
                @reservation = Reservation.create!(localParams.merge(:listing_id => @listing.id))
                flash[:success] = "Reservation #{@reservation.name} was created successfully!"
            end
        rescue ActiveRecord::RecordInvalid, ArgumentError
            flash[:deny] = "Name, start date, and end date is required for new reservation."
        end
        
        redirect_to listing_path(:id => @listing.id)
    end
    
    def destroy
        @listing = Listing.find(params[:listing_id])
        @reservation = Reservation.find(params[:id])
        @reservation.destroy
        
        flash[:success] = "Reservation '#{@reservation.name}' deleted"
        redirect_to listing_path(@listing)
    end
    
    def show
        @listing = Listing.find(params[:listing_id])
        @reservation = Reservation.find(params[:id])
    end
end

app/views/reservations/new.html.erb
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
<h2>Create New Reservation for Listing <%= @listing.name %></h2>

<%= form_tag listing_reservations_path(:id => @listing.id), :method => :post do %>
  <%= label :reservation, :name, 'Reservation Name' %>
  <%= text_field :reservation, :name %>
  <%= label :reservation, :start_date, "Start Date" %>
  <%= date_field :reservation, :start_date %>
  <%= label :reservation,:end_date, "End Date" %>
  <%= date_field :reservation, :end_date %>

<div id = "footer">
<table>
<% end %>
<td><%= button_to 'Go Back', listing_path(:id => @listing.id), :method => :get %></td>

<td><%= submit_tag 'Create Reservation' %></td>
</table>
</div>

app/views/reservations/show.html.erb
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
<h2>Details about <%= @reservation.name %> in Listing <%= @listing.name %> </h2>
<ul id="details">
  <li>
    Name:
    <%= @reservation.name %>
  </li>
  <li>
    Time Created:
    <%= @reservation.time_created.strftime("%B %d, %Y ") + @reservation.time_created.strftime("%H:%M")%>
  </li>
  <li>
    Start Date:
    <%= @reservation.start_date.strftime("%B %d, %Y ")%>
  </li>
  <li>
    End Date:
    <%= @reservation.end_date.strftime("%B %d, %Y ")%>
  </li>
</ul>

<div id ="footer">
<table id = "buttons_table" >
  <th><%= button_to 'Go Back', listing_path(@listing), :method => :get %></th>    
  <th><%= button_to 'Delete Reservation', listing_reservation_path(@reservation, :listing_id => @reservation.listing_id), :method => :delete %> </th>
  
</table>
</div>